/*
 * List of error constants to use throughout.
 */
const errorConstants = {
  // IDCS ErrorCodes
  LOGIN_CTX_EXPIRED_CODE: "AUTH-1120",
  SIGN_ON_POLICY_DENY: "AUTH-3033",
  WRONG_USER_PASS: "AUTH-3001",
  PASSWORD_MUST_CHANGE: "AUTH-3005",
  PASSWORD_EXPIRED:"AUTH-3004",
  APPROVAL_PENDING:"AUTH-1108",
  MAX_MFA_ATTEMPTS:"AUTH-1027",
  USER_MISMATCH:"AUTH-3023",

  // Reset Password error codes:
  RESET_PASSWD_INVALID_PASSWD: "error.identity.passwordmgmt.invalidCurrentPassword",
  RESET_PASSWD_POLICY_VIOLATION: "error.identity.passwordmgmt.pwdpolicyViolation",

  // IDCS Errors
  INVALID_IDCS_CONFIG:"EBADCONFIG",
  IDCS_AUTHN_FAILED:"EUNAUTH",
  ERROR_PARSING_RESPONSE_FROM_IDCS:"EBADPARSE",
  NO_TOKEN_FROM_IDCS:"ENOTOKEN",
  NO_KEY_FROM_IDCS:"ENOKEY",
  IDCS_KEY_INVALID:"EKEYINVALID",
  SUBMIT_CREDENTIALS_ARGS_INVALID:"EBADCREDS",
  IDCS_INTERNAL_ERROR_CRED_SUBMIT:"EIDCSCRED",
  IDCS_CONNECT_ERROR_CRED_SUBMIT:"ECONNCRED",
  SESSION_CREATE_FAILED:"ESESSCREA",
  COULD_NOT_CREATE_TOKEN:"ESESSTOKC",
  NO_COUNTRY_CODES:"ERETNOCC",

  // Invocation errors
  INVALID_OPERATION_FOR_ENDPOINT:"EINVALIDOP",
  SUBMIT_CREDS_MISSING_FIELDS:"ECREDREQ",
  CREATE_SESSION_MISSING_FIELDS:"ESESSREQ",
  SIGNATURE_VALIDATION_FAILED_FOR_LOGINCTX:"ELOGCTXSIG",
  UNABLE_TO_PARSE_LOGINCTX:"EINVLOGCTX",
  LOGIN_POST_MISSING_FIELDS:"EINVLOGREQ",
  CLEAR_KMSI_MISSING_FIELDS:"ECLKMSIREQ",
  CLEAR_KMSI_INVALID_CHARS:"ECLKMSIFMT",
  ENROLLMENT_MISSING_FIELDS:"EENROLLREQ",
  RESEND_MISSING_FIELDS:"ERESENDREQ",
  SET_PASSWORD_MISSING_FIELDS:"ESETPWREQ",
  FORGOT_PASSWORD_MISSING_FIELDS:"EFORPWREQ",
  BACKUP_FACTORS_MISSING_FIELDS:"EBKUPREQ",

  CRED_SUBMISSION_FAILED:"ECREDFAIL",
  CRED_SUBMISSION_NO_STATUS:"ENOCREDSTAT",
  ENROLLMENT_SUBMISSION_FAILED:"EENROLLFAIL",
  RESEND_CODE_FAILED:"ERSENDFAIL",
  BACKUP_FACTORS_FAILED:"EBKUPFAIL",

  RECOVERY_DETAILS_FAILED:"ERECFAIL",
  RECOVERY_INITATION_FAILED:"ERECIFAIL",
  RECOVERY_VALIDATION_FAILED:"ERECVFAIL"

}


export default errorConstants;